using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Shopify.Unity;
public static class CurrencySynbol
{
    public static string GetCurrencySimbol(CurrencyCode code)
    {
        switch(code)
        {
            case CurrencyCode.UNKNOWN: return "$"; break;
            case CurrencyCode.ALL: return "Lek"; break;
            case CurrencyCode.AFN: return "؋"; break;
            case CurrencyCode.ARS: return "$"; break;
            case CurrencyCode.AWG: return "ƒ"; break;
            case CurrencyCode.AUD: return "$"; break;
            case CurrencyCode.AZN: return "₼"; break;
            case CurrencyCode.BSD: return "$"; break;
            case CurrencyCode.BBD: return "$"; break;
            //case CurrencyCode.BYN: return "	Br	"; break;
            case CurrencyCode.BZD: return "BZ$"; break;
            case CurrencyCode.BMD: return "$"; break;
            case CurrencyCode.BOB: return "$b"; break;
            case CurrencyCode.BAM: return "KM"; break;
            case CurrencyCode.BWP: return "P"; break;
            case CurrencyCode.BGN: return "лв"; break;
            case CurrencyCode.BRL: return "R$"; break;
            case CurrencyCode.BND: return "$"; break;
            case CurrencyCode.KHR: return "៛"; break;
            case CurrencyCode.CAD: return "$"; break;
            case CurrencyCode.KYD: return "$"; break;
            case CurrencyCode.CLP: return "$"; break;
            case CurrencyCode.CNY: return "¥"; break;
            case CurrencyCode.COP: return "$"; break;
            case CurrencyCode.CRC: return "₡"; break;
            case CurrencyCode.HRK: return "kn"; break;
            //case CurrencyCode.CUP: return "	₱	"; break;
            case CurrencyCode.CZK: return "Kč"; break;
            case CurrencyCode.DKK: return "kr"; break;
            case CurrencyCode.DOP: return "RD$"; break;
            case CurrencyCode.XCD: return "$"; break;
            case CurrencyCode.EGP: return "£"; break;
            //case CurrencyCode.SVC: return "	$	"; break;
            case CurrencyCode.EUR: return "€"; break;
            case CurrencyCode.FKP: return "£"; break;
            case CurrencyCode.FJD: return "$"; break;
            case CurrencyCode.GHS: return "¢"; break;
            case CurrencyCode.GIP: return "£"; break;
            case CurrencyCode.GTQ: return "Q"; break;
            //case CurrencyCode.GGP: return "	£	"; break;
            case CurrencyCode.GYD: return "$"; break;
            case CurrencyCode.HNL: return "L"; break;
            case CurrencyCode.HKD: return "$"; break;
            case CurrencyCode.HUF: return "Ft"; break;
            case CurrencyCode.ISK: return "kr"; break;
            case CurrencyCode.INR: return "₹"; break;
            case CurrencyCode.IDR: return "Rp"; break;
            case CurrencyCode.IRR: return "﷼"; break;
            //case CurrencyCode.IMP: return "	£	"; break;
            case CurrencyCode.ILS: return "₪"; break;
            case CurrencyCode.JMD: return "J$"; break;
            case CurrencyCode.JPY: return "¥"; break;
            case CurrencyCode.JEP: return "£"; break;
            case CurrencyCode.KZT: return "лв"; break;
            //case CurrencyCode.KPW: return "	₩	"; break;
            case CurrencyCode.KRW: return "₩"; break;
            case CurrencyCode.KGS: return "лв"; break;
            case CurrencyCode.LAK: return "₭"; break;
            case CurrencyCode.LBP: return "£"; break;
            case CurrencyCode.LRD: return "$"; break;
            case CurrencyCode.MKD: return "ден"; break;
            case CurrencyCode.MYR: return "RM"; break;
            case CurrencyCode.MUR: return "₨"; break;
            case CurrencyCode.MXN: return "$"; break;
            case CurrencyCode.MNT: return "₮"; break;
            //case CurrencyCode.MNT: return "	د.إ	"; break;
            case CurrencyCode.MZN: return "MT"; break;
            case CurrencyCode.NAD: return "$"; break;
            case CurrencyCode.NPR: return "₨"; break;
            case CurrencyCode.ANG: return "ƒ"; break;
            case CurrencyCode.NZD: return "$"; break;
            case CurrencyCode.NIO: return "C$"; break;
            case CurrencyCode.NGN: return "₦"; break;
            case CurrencyCode.NOK: return "kr"; break;
            case CurrencyCode.OMR: return "﷼"; break;
            case CurrencyCode.PKR: return "₨"; break;
            case CurrencyCode.PAB: return "B/."; break;
            case CurrencyCode.PYG: return "Gs"; break;
            case CurrencyCode.PEN: return "S/."; break;
            case CurrencyCode.PHP: return "₱"; break;
            case CurrencyCode.PLN: return "zł"; break;
            case CurrencyCode.QAR: return "﷼"; break;
            case CurrencyCode.RON: return "lei"; break;
            case CurrencyCode.RUB: return "₽"; break;
            case CurrencyCode.SHP: return "£"; break;
            case CurrencyCode.SAR: return "﷼"; break;
            case CurrencyCode.RSD: return "Дин."; break;
            case CurrencyCode.SCR: return "₨"; break;
            case CurrencyCode.SGD: return "$"; break;
            case CurrencyCode.SBD: return "$"; break;
            //case CurrencyCode.SOS: return "	S	"; break;
            case CurrencyCode.ZAR: return "R"; break;
            case CurrencyCode.LKR: return "₨"; break;
            case CurrencyCode.SEK: return "kr"; break;
            case CurrencyCode.CHF: return "CHF"; break;
            case CurrencyCode.SRD: return "$"; break;
            case CurrencyCode.SYP: return "£"; break;
            case CurrencyCode.TWD: return "NT$"; break;
            case CurrencyCode.THB: return "฿"; break;
            case CurrencyCode.TTD: return "TT$"; break;
            case CurrencyCode.TRY: return "₺"; break;
            //case CurrencyCode.TVD: return "	$	"; break;
            case CurrencyCode.UAH: return "₴"; break;
            case CurrencyCode.AED: return "د.إ"; break;
            case CurrencyCode.GBP: return "£"; break;
            case CurrencyCode.USD: return "$"; break;
            case CurrencyCode.UYU: return "$U"; break;
            case CurrencyCode.UZS: return "лв"; break;
            //case CurrencyCode.VEF: return "	Bs	"; break;
            case CurrencyCode.VND: return "₫"; break;
            case CurrencyCode.YER: return "﷼"; break;
            //case CurrencyCode.ZWD: return "	Z$	"; break;
            default:
                return "$";
                break;
        }
    }
}